apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/frontend
- ../../base/image-acquirer
- ../../base/mqtt
- image-acquirer-configmap.yaml
- image-acquirer-pvc.yaml

patches:
- target: 
    kind: Deployment
    name: image-acquirer
  path: image-acquirer-patch.yaml
