apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/accelerator-name: migrated-gpu
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: koboldcpp ServingRuntime for KServe
    opendatahub.io/template-name: koboldcpp
    openshift.io/display-name: llava
  labels:
    opendatahub.io/dashboard: "true"
  name: llava
spec:
  multiModel: false
  supportedModelFormats:
  - name: gguf
    autoSelect: true
  containers:
  - name: kserve-container
    image: quay.io/kwkoo/koboldcpp-openshift
    ports:
    - containerPort: 5001
    env:
    - name: "EXTRA_ARGS"
      value: "--gpulayers 999 --usecublas normal"
    livenessProbe:
     httpGet:
       path: /api/v1/info/version
       port: 5001
     initialDelaySeconds: 600
    readinessProbe:
     httpGet:
       path: /api/v1/info/version
       port: 5001
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory