apiVersion: v1
stringData:
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: "minio.demo.svc:9000"
    serving.kserve.io/s3-usehttps: "0"
  name: kserve-secret