kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-models
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: models
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  AWS_DEFAULT_REGION: ""
  AWS_S3_BUCKET: "models"
  AWS_S3_ENDPOINT: "http://minio:9000"
type: Opaque