apiVersion: v1
data:
  mosquitto.conf: |
    max_queued_messages 5

    listener 1883 0.0.0.0
    protocol mqtt
    allow_anonymous true

    listener 9001 0.0.0.0
    protocol websockets
    allow_anonymous true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mosquitto